# Generated by Django 2.2.2 on 2019-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='potato', max_length=500),
            preserve_default=False,
        ),
    ]
